import java.awt.*;
import java.awt.font.*;
import java.awt.geom.*;
import java.io.*;
import java.nio.charset.StandardCharsets;

/**
 * Ширины знаков шрифта подписи Ramus — Dialog 8 — и генератор glyphs.go.
 *
 * Запуск из этого каталога: javac Glyphs.java && java -Djava.awt.headless=true Glyphs
 *
 * Печатает проверку (ширина строки равна сумме ширин знаков; сколько знаков
 * расходятся у Dialog и Liberation Sans) и пишет
 * ../../../ramusc/internal/generate/glyphs.go.
 *
 * FontRenderContext — без сглаживания и дробных метрик, как PStringBounder у
 * Ramus: ширины целые, и ширина строки — их сумма.
 */
public class Glyphs {
    static final FontRenderContext FRC = new FontRenderContext(new AffineTransform(), false, false);

    static double w(Font f, String s) {
        return f.getStringBounds(s, FRC).getWidth();
    }

    public static void main(String[] a) throws IOException {
        // Linux: логический Dialog — DejaVu Sans. Windows: Arial; здесь его
        // представляет Liberation Sans, метрически с ним совпадающий.
        Font d = new Font("Dialog", Font.PLAIN, 8), l = new Font("Liberation Sans", Font.PLAIN, 8);

        StringBuilder chars = new StringBuilder();
        for (char c = 0x20; c < 0x7f; c++) chars.append(c);
        for (char c = 0x410; c <= 0x44f; c++) chars.append(c);
        chars.append('Ё').append('ё').append('«').append('»').append('—').append('–').append('№');
        char[] sorted = chars.toString().toCharArray();
        java.util.Arrays.sort(sorted);

        int diff = 0, maxAdv = 0;
        String[] lits = new String[sorted.length];
        int[] advs = new int[sorted.length];
        int widest = 0;
        for (int i = 0; i < sorted.length; i++) {
            char c = sorted[i];
            int a1 = (int) Math.round(w(d, "" + c)), a2 = (int) Math.round(w(l, "" + c));
            if (a1 != a2) diff++;
            advs[i] = Math.max(a1, a2);
            maxAdv = Math.max(maxAdv, advs[i]);
            lits[i] = c == '\'' ? "'\\''" : c == '\\' ? "'\\\\'" : "'" + c + "'";
            widest = Math.max(widest, lits[i].length());
        }
        // Значения выровнены так же, как это сделал бы gofmt: файл выходит
        // готовым, без второго шага, и повторная генерация даёт те же байты.
        StringBuilder table = new StringBuilder();
        for (int i = 0; i < sorted.length; i++)
            table.append(String.format("\t%-" + (widest + 1) + "s %d,%n", lits[i] + ":", advs[i]));
        System.out.println("знаков " + sorted.length + ", разных у Dialog и Liberation: " + diff + ", наибольший " + maxAdv);

        String[] probes = {"Рецепт приготовления чахохбили", "Швеёно-вышивальгая машинка", "Помидоры",
                "Растительное масло", "Хмели-сунели", "Детали изделия"};
        for (String p : probes) {
            double sum = 0;
            for (char c : p.toCharArray()) sum += w(d, "" + c);
            System.out.printf("%-32s строкой %.0f, суммой знаков %.0f%n", p, w(d, p), sum);
        }

        try (Writer out = new OutputStreamWriter(
                new FileOutputStream("../../../ramusc/internal/generate/glyphs.go"), StandardCharsets.UTF_8)) {
            out.write("// Code generated by specs/013-arrow-label-overlap/evidence/Glyphs.java; DO NOT EDIT.\n\n");
            out.write("package generate\n\n");
            out.write("// glyphWidth — ширина знака подписи в единицах листа Ramus.\n");
            out.write("//\n");
            out.write("// Шрифт подписи — Dialog 8 (VISUAL_ATTRIBUTES сектора). Ширина — наибольшая\n");
            out.write("// из двух систем: на Linux Dialog — это DejaVu Sans, на Windows — Arial\n");
            out.write("// (снят с метрически совпадающего Liberation Sans). Так таблица не меньше\n");
            out.write("// настоящей ширины ни на одной из них, и рамка не режет слово.\n");
            out.write("var glyphWidth = map[rune]float64{\n");
            out.write(table.toString());
            out.write("}\n\n");
            out.write("// glyphFallback — ширина знака, которого нет в таблице: самый широкий из\n");
            out.write("// известных. Рамка шире текста безопасна — Ramus её ужмёт, а уже — нет.\n");
            out.write("const glyphFallback = " + maxAdv + "\n");
        }
    }
}
